from abc import ABC, abstractmethod
from typing import Any
from app.services.detection.models import Detection
from app.services.telemetry.process_tree.models import ProcessTree, ProcessNode


class DetectionRule(ABC):
    """
    Abstract base class for all deterministic behavior detection rules.
    """

    @property
    @abstractmethod
    def id(self) -> str:
        """Globally unique identifier for the rule."""
        pass

    @property
    @abstractmethod
    def name(self) -> str:
        """Human-readable name of the rule."""
        pass

    @property
    @abstractmethod
    def description(self) -> str:
        """Detailed description of what the rule detects."""
        pass

    @property
    @abstractmethod
    def severity(self) -> str:
        """Severity level (LOW, MEDIUM, HIGH, CRITICAL)."""
        pass

    @property
    @abstractmethod
    def mitre_technique(self) -> str:
        """Associated MITRE ATT&CK Technique ID (e.g. T1059)."""
        pass

    @property
    @abstractmethod
    def mitre_tactic(self) -> str:
        """Associated MITRE ATT&CK Tactic name."""
        pass

    @property
    @abstractmethod
    def confidence(self) -> int:
        """Confidence score from 0 to 100."""
        pass

    @property
    @abstractmethod
    def recommendations(self) -> list[str]:
        """List of recommended remediation actions."""
        pass

    @property
    @abstractmethod
    def tags(self) -> list[str]:
        """List of tags for classification."""
        pass

    @abstractmethod
    def evaluate(self, tree: ProcessTree) -> list[Detection]:
        """
        Evaluate the rule against a ProcessTree.
        Returns:
            list[Detection] generated by this rule.
        """
        pass

    def _create_detection(
        self,
        node: ProcessNode,
        host_id: str,
        matched_keywords: list[str],
        matched_processes: list[str],
        evidence: list[dict[str, Any]],
        future_extensions: dict[str, Any] = None,
    ) -> Detection:
        """
        Helper to construct a deterministic, immutable Detection object.
        """
        import hashlib

        # Deterministic unique detection ID
        raw_id_str = f"{self.id}:{host_id}:{node.process_guid}"
        det_hash = hashlib.sha256(raw_id_str.encode()).hexdigest()
        det_id = f"det_{det_hash}"

        return Detection(
            id=det_id,
            rule_id=self.id,
            title=self.name,
            description=self.description,
            severity=self.severity,
            confidence=self.confidence,
            host_id=host_id,
            process_guid=node.process_guid,
            timestamp=node.create_time,
            mitre_technique=self.mitre_technique,
            mitre_tactic=self.mitre_tactic,
            recommendations=self.recommendations,
            evidence=evidence,
            metadata={
                "rule_version": "1.0.0",
                "matched_keywords": matched_keywords,
                "matched_processes": matched_processes,
                "future_extensions": future_extensions or {},
            },
        )

    def _get_node_evidence(self, node: ProcessNode) -> dict[str, Any]:
        """
        Build standard structured evidence for a process node.
        """
        return {
            "Process Name": node.process_name,
            "PID": node.pid,
            "Parent PID": node.ppid,
            "Command Line": " ".join(node.cmdline) if isinstance(node.cmdline, list) else node.cmdline,
            "Executable": node.exe,
            "Username": node.username,
            "Parent Process": node.parent.process_name if node.parent else None,
            "Matched Rule": self.id,
        }


